# Generated by Django 3.1.5 on 2021-01-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
